on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     xray:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
      ref: context.event.github.ref
  Xray:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    inputs:
      xray: CloneRepo.outputs.xray
    outputs:
      xrayoutputs:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        cd /inputs/xray/classification-challenge/classification-challenge-starter
        python classification-challenge.py 
      image: tensorflow/tensorflow:1.14.0-gpu-py3
